# coding: utf-8

"""
    BIPAD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bipad_api
from bipad_api.models.inline_response20043 import InlineResponse20043  # noqa: E501
from bipad_api.rest import ApiException


class TestInlineResponse20043(unittest.TestCase):
    """InlineResponse20043 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20043(self):
        """Test InlineResponse20043"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bipad_api.models.inline_response20043.InlineResponse20043()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
