# coding: utf-8

"""
    BIPAD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bipad_api
from bipad_api.models.demographic import Demographic  # noqa: E501
from bipad_api.rest import ApiException


class TestDemographic(unittest.TestCase):
    """Demographic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDemographic(self):
        """Test Demographic"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bipad_api.models.demographic.Demographic()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
