# coding: utf-8

"""
    BIPAD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bipad_api
from bipad.api_api import ApiApi  # noqa: E501
from bipad_api.rest import ApiException


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = bipad.api_api.ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_agriculture_type_list(self):
        """Test case for api_agriculture_type_list

        """
        pass

    def test_api_agriculture_type_read(self):
        """Test case for api_agriculture_type_read

        """
        pass

    def test_api_alert_list(self):
        """Test case for api_alert_list

        """
        pass

    def test_api_alert_read(self):
        """Test case for api_alert_read

        """
        pass

    def test_api_citizen_report_create(self):
        """Test case for api_citizen_report_create

        """
        pass

    def test_api_citizen_report_list(self):
        """Test case for api_citizen_report_list

        """
        pass

    def test_api_citizen_report_read(self):
        """Test case for api_citizen_report_read

        """
        pass

    def test_api_contact_training_list(self):
        """Test case for api_contact_training_list

        """
        pass

    def test_api_contact_training_read(self):
        """Test case for api_contact_training_read

        """
        pass

    def test_api_country_list(self):
        """Test case for api_country_list

        """
        pass

    def test_api_country_read(self):
        """Test case for api_country_read

        """
        pass

    def test_api_covid19_case_list(self):
        """Test case for api_covid19_case_list

        """
        pass

    def test_api_covid19_case_read(self):
        """Test case for api_covid19_case_read

        """
        pass

    def test_api_covid19_immigrant_country_list(self):
        """Test case for api_covid19_immigrant_country_list

        """
        pass

    def test_api_covid19_immigrant_country_read(self):
        """Test case for api_covid19_immigrant_country_read

        """
        pass

    def test_api_covid19_immigrant_create(self):
        """Test case for api_covid19_immigrant_create

        """
        pass

    def test_api_covid19_immigrant_district_list(self):
        """Test case for api_covid19_immigrant_district_list

        """
        pass

    def test_api_covid19_immigrant_district_read(self):
        """Test case for api_covid19_immigrant_district_read

        """
        pass

    def test_api_covid19_immigrant_list(self):
        """Test case for api_covid19_immigrant_list

        """
        pass

    def test_api_covid19_immigrant_read(self):
        """Test case for api_covid19_immigrant_read

        """
        pass

    def test_api_covid19_nationalinfo_list(self):
        """Test case for api_covid19_nationalinfo_list

        """
        pass

    def test_api_covid19_nationalinfo_read(self):
        """Test case for api_covid19_nationalinfo_read

        """
        pass

    def test_api_covid19_quarantineinfo_create(self):
        """Test case for api_covid19_quarantineinfo_create

        """
        pass

    def test_api_covid19_quarantineinfo_delete(self):
        """Test case for api_covid19_quarantineinfo_delete

        """
        pass

    def test_api_covid19_quarantineinfo_list(self):
        """Test case for api_covid19_quarantineinfo_list

        """
        pass

    def test_api_covid19_quarantineinfo_partial_update(self):
        """Test case for api_covid19_quarantineinfo_partial_update

        """
        pass

    def test_api_covid19_quarantineinfo_read(self):
        """Test case for api_covid19_quarantineinfo_read

        """
        pass

    def test_api_covid19_quarantineinfo_update(self):
        """Test case for api_covid19_quarantineinfo_update

        """
        pass

    def test_api_covid19_situationreport_list(self):
        """Test case for api_covid19_situationreport_list

        """
        pass

    def test_api_covid19_travelhistory_list(self):
        """Test case for api_covid19_travelhistory_list

        """
        pass

    def test_api_covid19_travelhistory_read(self):
        """Test case for api_covid19_travelhistory_read

        """
        pass

    def test_api_covid19_verifiedimmigrant_list(self):
        """Test case for api_covid19_verifiedimmigrant_list

        """
        pass

    def test_api_covid19_verifiedimmigrant_read(self):
        """Test case for api_covid19_verifiedimmigrant_read

        """
        pass

    def test_api_demographic_list(self):
        """Test case for api_demographic_list

        """
        pass

    def test_api_demographic_read(self):
        """Test case for api_demographic_read

        """
        pass

    def test_api_disability_type_list(self):
        """Test case for api_disability_type_list

        """
        pass

    def test_api_disability_type_read(self):
        """Test case for api_disability_type_read

        """
        pass

    def test_api_district_list(self):
        """Test case for api_district_list

        """
        pass

    def test_api_district_read(self):
        """Test case for api_district_read

        """
        pass

    def test_api_document_category_list(self):
        """Test case for api_document_category_list

        """
        pass

    def test_api_document_category_read(self):
        """Test case for api_document_category_read

        """
        pass

    def test_api_document_list(self):
        """Test case for api_document_list

        """
        pass

    def test_api_document_read(self):
        """Test case for api_document_read

        """
        pass

    def test_api_earthquake_list(self):
        """Test case for api_earthquake_list

        """
        pass

    def test_api_earthquake_read(self):
        """Test case for api_earthquake_read

        """
        pass

    def test_api_earthquake_riskscore_list(self):
        """Test case for api_earthquake_riskscore_list

        """
        pass

    def test_api_earthquake_riskscore_read(self):
        """Test case for api_earthquake_riskscore_read

        """
        pass

    def test_api_enum_choice_list(self):
        """Test case for api_enum_choice_list

        """
        pass

    def test_api_event_list(self):
        """Test case for api_event_list

        """
        pass

    def test_api_event_read(self):
        """Test case for api_event_read

        """
        pass

    def test_api_fire_list(self):
        """Test case for api_fire_list

        """
        pass

    def test_api_fire_read(self):
        """Test case for api_fire_read

        """
        pass

    def test_api_fiscal_year_list(self):
        """Test case for api_fiscal_year_list

        """
        pass

    def test_api_fiscal_year_read(self):
        """Test case for api_fiscal_year_read

        """
        pass

    def test_api_hazard_list(self):
        """Test case for api_hazard_list

        """
        pass

    def test_api_hazard_read(self):
        """Test case for api_hazard_read

        """
        pass

    def test_api_incident_feedback_create(self):
        """Test case for api_incident_feedback_create

        """
        pass

    def test_api_incident_feedback_list(self):
        """Test case for api_incident_feedback_list

        """
        pass

    def test_api_incident_feedback_read(self):
        """Test case for api_incident_feedback_read

        """
        pass

    def test_api_incident_list(self):
        """Test case for api_incident_list

        """
        pass

    def test_api_incident_profile_list(self):
        """Test case for api_incident_profile_list

        """
        pass

    def test_api_incident_profile_read(self):
        """Test case for api_incident_profile_read

        """
        pass

    def test_api_incident_read(self):
        """Test case for api_incident_read

        """
        pass

    def test_api_infrastructure_type_list(self):
        """Test case for api_infrastructure_type_list

        """
        pass

    def test_api_infrastructure_type_read(self):
        """Test case for api_infrastructure_type_read

        """
        pass

    def test_api_infrastructure_unit_list(self):
        """Test case for api_infrastructure_unit_list

        """
        pass

    def test_api_infrastructure_unit_read(self):
        """Test case for api_infrastructure_unit_read

        """
        pass

    def test_api_inventory_category_list(self):
        """Test case for api_inventory_category_list

        """
        pass

    def test_api_inventory_category_read(self):
        """Test case for api_inventory_category_read

        """
        pass

    def test_api_inventory_item_list(self):
        """Test case for api_inventory_item_list

        """
        pass

    def test_api_inventory_item_read(self):
        """Test case for api_inventory_item_read

        """
        pass

    def test_api_inventory_list(self):
        """Test case for api_inventory_list

        """
        pass

    def test_api_inventory_read(self):
        """Test case for api_inventory_read

        """
        pass

    def test_api_layer_group_list(self):
        """Test case for api_layer_group_list

        """
        pass

    def test_api_layer_group_read(self):
        """Test case for api_layer_group_read

        """
        pass

    def test_api_layer_list(self):
        """Test case for api_layer_list

        """
        pass

    def test_api_layer_read(self):
        """Test case for api_layer_read

        """
        pass

    def test_api_livestock_type_list(self):
        """Test case for api_livestock_type_list

        """
        pass

    def test_api_livestock_type_read(self):
        """Test case for api_livestock_type_read

        """
        pass

    def test_api_loss_agriculture_list(self):
        """Test case for api_loss_agriculture_list

        """
        pass

    def test_api_loss_agriculture_read(self):
        """Test case for api_loss_agriculture_read

        """
        pass

    def test_api_loss_family_list(self):
        """Test case for api_loss_family_list

        """
        pass

    def test_api_loss_family_read(self):
        """Test case for api_loss_family_read

        """
        pass

    def test_api_loss_infrastructure_list(self):
        """Test case for api_loss_infrastructure_list

        """
        pass

    def test_api_loss_infrastructure_read(self):
        """Test case for api_loss_infrastructure_read

        """
        pass

    def test_api_loss_list(self):
        """Test case for api_loss_list

        """
        pass

    def test_api_loss_livestock_list(self):
        """Test case for api_loss_livestock_list

        """
        pass

    def test_api_loss_livestock_read(self):
        """Test case for api_loss_livestock_read

        """
        pass

    def test_api_loss_people_list(self):
        """Test case for api_loss_people_list

        """
        pass

    def test_api_loss_people_read(self):
        """Test case for api_loss_people_read

        """
        pass

    def test_api_loss_read(self):
        """Test case for api_loss_read

        """
        pass

    def test_api_manual_list(self):
        """Test case for api_manual_list

        """
        pass

    def test_api_manual_read(self):
        """Test case for api_manual_read

        """
        pass

    def test_api_metadata_list(self):
        """Test case for api_metadata_list

        """
        pass

    def test_api_metadata_read(self):
        """Test case for api_metadata_read

        """
        pass

    def test_api_municipality_contact_list(self):
        """Test case for api_municipality_contact_list

        """
        pass

    def test_api_municipality_contact_read(self):
        """Test case for api_municipality_contact_read

        """
        pass

    def test_api_municipality_covid19_info_list(self):
        """Test case for api_municipality_covid19_info_list

        """
        pass

    def test_api_municipality_covid19_info_read(self):
        """Test case for api_municipality_covid19_info_read

        """
        pass

    def test_api_municipality_list(self):
        """Test case for api_municipality_list

        """
        pass

    def test_api_municipality_read(self):
        """Test case for api_municipality_read

        """
        pass

    def test_api_nap_precipitation_list(self):
        """Test case for api_nap_precipitation_list

        """
        pass

    def test_api_nap_precipitation_read(self):
        """Test case for api_nap_precipitation_read

        """
        pass

    def test_api_nap_temperature_list(self):
        """Test case for api_nap_temperature_list

        """
        pass

    def test_api_nap_temperature_read(self):
        """Test case for api_nap_temperature_read

        """
        pass

    def test_api_organization_list(self):
        """Test case for api_organization_list

        """
        pass

    def test_api_organization_read(self):
        """Test case for api_organization_read

        """
        pass

    def test_api_pollution_list(self):
        """Test case for api_pollution_list

        """
        pass

    def test_api_pollution_read(self):
        """Test case for api_pollution_read

        """
        pass

    def test_api_project_list(self):
        """Test case for api_project_list

        """
        pass

    def test_api_project_read(self):
        """Test case for api_project_read

        """
        pass

    def test_api_province_list(self):
        """Test case for api_province_list

        """
        pass

    def test_api_province_read(self):
        """Test case for api_province_read

        """
        pass

    def test_api_rain_list(self):
        """Test case for api_rain_list

        """
        pass

    def test_api_rain_read(self):
        """Test case for api_rain_read

        """
        pass

    def test_api_reconstruction_list(self):
        """Test case for api_reconstruction_list

        """
        pass

    def test_api_reconstruction_read(self):
        """Test case for api_reconstruction_read

        """
        pass

    def test_api_relief_release_status_list(self):
        """Test case for api_relief_release_status_list

        """
        pass

    def test_api_relief_release_status_read(self):
        """Test case for api_relief_release_status_read

        """
        pass

    def test_api_resource_list(self):
        """Test case for api_resource_list

        """
        pass

    def test_api_resource_profile_list(self):
        """Test case for api_resource_profile_list

        """
        pass

    def test_api_resource_profile_read(self):
        """Test case for api_resource_profile_read

        """
        pass

    def test_api_resource_read(self):
        """Test case for api_resource_read

        """
        pass

    def test_api_river_list(self):
        """Test case for api_river_list

        """
        pass

    def test_api_river_read(self):
        """Test case for api_river_read

        """
        pass

    def test_api_situation_report_list(self):
        """Test case for api_situation_report_list

        """
        pass

    def test_api_situation_report_read(self):
        """Test case for api_situation_report_read

        """
        pass

    def test_api_streamflow_list(self):
        """Test case for api_streamflow_list

        """
        pass

    def test_api_streamflow_read(self):
        """Test case for api_streamflow_read

        """
        pass

    def test_api_token_create(self):
        """Test case for api_token_create

        """
        pass

    def test_api_token_refresh_create(self):
        """Test case for api_token_refresh_create

        """
        pass

    def test_api_token_verify_create(self):
        """Test case for api_token_verify_create

        """
        pass

    def test_api_v1_auth_login_create(self):
        """Test case for api_v1_auth_login_create

        """
        pass

    def test_api_v1_geolookup_list(self):
        """Test case for api_v1_geolookup_list

        """
        pass

    def test_api_vulnerability_list(self):
        """Test case for api_vulnerability_list

        """
        pass

    def test_api_vulnerability_read(self):
        """Test case for api_vulnerability_read

        """
        pass

    def test_api_ward_list(self):
        """Test case for api_ward_list

        """
        pass

    def test_api_ward_read(self):
        """Test case for api_ward_read

        """
        pass

    def test_api_weather_list(self):
        """Test case for api_weather_list

        """
        pass

    def test_api_weather_read(self):
        """Test case for api_weather_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
