# coding: utf-8

"""
    BIPAD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bipad_api
from bipad_api.models.metadata import Metadata  # noqa: E501
from bipad_api.rest import ApiException


class TestMetadata(unittest.TestCase):
    """Metadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadata(self):
        """Test Metadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bipad_api.models.metadata.Metadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
