# coding: utf-8

"""
    BIPAD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bipad_api
from bipad_api.models.inline_response20037 import InlineResponse20037  # noqa: E501
from bipad_api.rest import ApiException


class TestInlineResponse20037(unittest.TestCase):
    """InlineResponse20037 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20037(self):
        """Test InlineResponse20037"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bipad_api.models.inline_response20037.InlineResponse20037()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
