# coding: utf-8

"""
    BIPAD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Alert(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'geojson': 'str',
        'title': 'str',
        'wards': 'list[int]',
        'point': 'str',
        'created_on': 'datetime',
        'source': 'str',
        'description': 'str',
        'verified': 'bool',
        'public': 'bool',
        'started_on': 'datetime',
        'expire_on': 'datetime',
        'polygon': 'str',
        'reference_type': 'str',
        'reference_data': 'str',
        'reference_id': 'int',
        'region': 'str',
        'region_id': 'int',
        'created_by': 'int',
        'updated_by': 'int',
        'hazard': 'int',
        'event': 'int'
    }

    attribute_map = {
        'id': 'id',
        'geojson': 'geojson',
        'title': 'title',
        'wards': 'wards',
        'point': 'point',
        'created_on': 'createdOn',
        'source': 'source',
        'description': 'description',
        'verified': 'verified',
        'public': 'public',
        'started_on': 'startedOn',
        'expire_on': 'expireOn',
        'polygon': 'polygon',
        'reference_type': 'referenceType',
        'reference_data': 'referenceData',
        'reference_id': 'referenceId',
        'region': 'region',
        'region_id': 'regionId',
        'created_by': 'createdBy',
        'updated_by': 'updatedBy',
        'hazard': 'hazard',
        'event': 'event'
    }

    def __init__(self, id=None, geojson=None, title=None, wards=None, point=None, created_on=None, source=None, description=None, verified=None, public=None, started_on=None, expire_on=None, polygon=None, reference_type=None, reference_data=None, reference_id=None, region=None, region_id=None, created_by=None, updated_by=None, hazard=None, event=None):  # noqa: E501
        """Alert - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._geojson = None
        self._title = None
        self._wards = None
        self._point = None
        self._created_on = None
        self._source = None
        self._description = None
        self._verified = None
        self._public = None
        self._started_on = None
        self._expire_on = None
        self._polygon = None
        self._reference_type = None
        self._reference_data = None
        self._reference_id = None
        self._region = None
        self._region_id = None
        self._created_by = None
        self._updated_by = None
        self._hazard = None
        self._event = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if geojson is not None:
            self.geojson = geojson
        if title is not None:
            self.title = title
        self.wards = wards
        self.point = point
        if created_on is not None:
            self.created_on = created_on
        if source is not None:
            self.source = source
        self.description = description
        if verified is not None:
            self.verified = verified
        if public is not None:
            self.public = public
        if started_on is not None:
            self.started_on = started_on
        if expire_on is not None:
            self.expire_on = expire_on
        if polygon is not None:
            self.polygon = polygon
        if reference_type is not None:
            self.reference_type = reference_type
        if reference_data is not None:
            self.reference_data = reference_data
        if reference_id is not None:
            self.reference_id = reference_id
        if region is not None:
            self.region = region
        if region_id is not None:
            self.region_id = region_id
        if created_by is not None:
            self.created_by = created_by
        if updated_by is not None:
            self.updated_by = updated_by
        if hazard is not None:
            self.hazard = hazard
        if event is not None:
            self.event = event

    @property
    def id(self):
        """Gets the id of this Alert.  # noqa: E501


        :return: The id of this Alert.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Alert.


        :param id: The id of this Alert.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def geojson(self):
        """Gets the geojson of this Alert.  # noqa: E501


        :return: The geojson of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._geojson

    @geojson.setter
    def geojson(self, geojson):
        """Sets the geojson of this Alert.


        :param geojson: The geojson of this Alert.  # noqa: E501
        :type: str
        """

        self._geojson = geojson

    @property
    def title(self):
        """Gets the title of this Alert.  # noqa: E501


        :return: The title of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Alert.


        :param title: The title of this Alert.  # noqa: E501
        :type: str
        """
        if title is not None and len(title) < 1:
            raise ValueError("Invalid value for `title`, length must be greater than or equal to `1`")  # noqa: E501

        self._title = title

    @property
    def wards(self):
        """Gets the wards of this Alert.  # noqa: E501


        :return: The wards of this Alert.  # noqa: E501
        :rtype: list[int]
        """
        return self._wards

    @wards.setter
    def wards(self, wards):
        """Sets the wards of this Alert.


        :param wards: The wards of this Alert.  # noqa: E501
        :type: list[int]
        """
        if wards is None:
            raise ValueError("Invalid value for `wards`, must not be `None`")  # noqa: E501

        self._wards = wards

    @property
    def point(self):
        """Gets the point of this Alert.  # noqa: E501


        :return: The point of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._point

    @point.setter
    def point(self, point):
        """Sets the point of this Alert.


        :param point: The point of this Alert.  # noqa: E501
        :type: str
        """
        if point is None:
            raise ValueError("Invalid value for `point`, must not be `None`")  # noqa: E501

        self._point = point

    @property
    def created_on(self):
        """Gets the created_on of this Alert.  # noqa: E501


        :return: The created_on of this Alert.  # noqa: E501
        :rtype: datetime
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """Sets the created_on of this Alert.


        :param created_on: The created_on of this Alert.  # noqa: E501
        :type: datetime
        """

        self._created_on = created_on

    @property
    def source(self):
        """Gets the source of this Alert.  # noqa: E501


        :return: The source of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this Alert.


        :param source: The source of this Alert.  # noqa: E501
        :type: str
        """
        allowed_values = ["dhm", "other", "nsc", "icimod", "doe"]  # noqa: E501
        if source not in allowed_values:
            raise ValueError(
                "Invalid value for `source` ({0}), must be one of {1}"  # noqa: E501
                .format(source, allowed_values)
            )

        self._source = source

    @property
    def description(self):
        """Gets the description of this Alert.  # noqa: E501


        :return: The description of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Alert.


        :param description: The description of this Alert.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501
        if description is not None and len(description) < 1:
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `1`")  # noqa: E501

        self._description = description

    @property
    def verified(self):
        """Gets the verified of this Alert.  # noqa: E501


        :return: The verified of this Alert.  # noqa: E501
        :rtype: bool
        """
        return self._verified

    @verified.setter
    def verified(self, verified):
        """Sets the verified of this Alert.


        :param verified: The verified of this Alert.  # noqa: E501
        :type: bool
        """

        self._verified = verified

    @property
    def public(self):
        """Gets the public of this Alert.  # noqa: E501


        :return: The public of this Alert.  # noqa: E501
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public):
        """Sets the public of this Alert.


        :param public: The public of this Alert.  # noqa: E501
        :type: bool
        """

        self._public = public

    @property
    def started_on(self):
        """Gets the started_on of this Alert.  # noqa: E501


        :return: The started_on of this Alert.  # noqa: E501
        :rtype: datetime
        """
        return self._started_on

    @started_on.setter
    def started_on(self, started_on):
        """Sets the started_on of this Alert.


        :param started_on: The started_on of this Alert.  # noqa: E501
        :type: datetime
        """

        self._started_on = started_on

    @property
    def expire_on(self):
        """Gets the expire_on of this Alert.  # noqa: E501


        :return: The expire_on of this Alert.  # noqa: E501
        :rtype: datetime
        """
        return self._expire_on

    @expire_on.setter
    def expire_on(self, expire_on):
        """Sets the expire_on of this Alert.


        :param expire_on: The expire_on of this Alert.  # noqa: E501
        :type: datetime
        """

        self._expire_on = expire_on

    @property
    def polygon(self):
        """Gets the polygon of this Alert.  # noqa: E501


        :return: The polygon of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._polygon

    @polygon.setter
    def polygon(self, polygon):
        """Sets the polygon of this Alert.


        :param polygon: The polygon of this Alert.  # noqa: E501
        :type: str
        """

        self._polygon = polygon

    @property
    def reference_type(self):
        """Gets the reference_type of this Alert.  # noqa: E501


        :return: The reference_type of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._reference_type

    @reference_type.setter
    def reference_type(self, reference_type):
        """Sets the reference_type of this Alert.


        :param reference_type: The reference_type of this Alert.  # noqa: E501
        :type: str
        """
        if reference_type is not None and len(reference_type) < 1:
            raise ValueError("Invalid value for `reference_type`, length must be greater than or equal to `1`")  # noqa: E501

        self._reference_type = reference_type

    @property
    def reference_data(self):
        """Gets the reference_data of this Alert.  # noqa: E501


        :return: The reference_data of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._reference_data

    @reference_data.setter
    def reference_data(self, reference_data):
        """Sets the reference_data of this Alert.


        :param reference_data: The reference_data of this Alert.  # noqa: E501
        :type: str
        """

        self._reference_data = reference_data

    @property
    def reference_id(self):
        """Gets the reference_id of this Alert.  # noqa: E501


        :return: The reference_id of this Alert.  # noqa: E501
        :rtype: int
        """
        return self._reference_id

    @reference_id.setter
    def reference_id(self, reference_id):
        """Sets the reference_id of this Alert.


        :param reference_id: The reference_id of this Alert.  # noqa: E501
        :type: int
        """
        if reference_id is not None and reference_id > 2147483647:  # noqa: E501
            raise ValueError("Invalid value for `reference_id`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if reference_id is not None and reference_id < 0:  # noqa: E501
            raise ValueError("Invalid value for `reference_id`, must be a value greater than or equal to `0`")  # noqa: E501

        self._reference_id = reference_id

    @property
    def region(self):
        """Gets the region of this Alert.  # noqa: E501


        :return: The region of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this Alert.


        :param region: The region of this Alert.  # noqa: E501
        :type: str
        """
        if region is not None and len(region) > 25:
            raise ValueError("Invalid value for `region`, length must be less than or equal to `25`")  # noqa: E501

        self._region = region

    @property
    def region_id(self):
        """Gets the region_id of this Alert.  # noqa: E501


        :return: The region_id of this Alert.  # noqa: E501
        :rtype: int
        """
        return self._region_id

    @region_id.setter
    def region_id(self, region_id):
        """Sets the region_id of this Alert.


        :param region_id: The region_id of this Alert.  # noqa: E501
        :type: int
        """
        if region_id is not None and region_id > 2147483647:  # noqa: E501
            raise ValueError("Invalid value for `region_id`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if region_id is not None and region_id < -2147483648:  # noqa: E501
            raise ValueError("Invalid value for `region_id`, must be a value greater than or equal to `-2147483648`")  # noqa: E501

        self._region_id = region_id

    @property
    def created_by(self):
        """Gets the created_by of this Alert.  # noqa: E501


        :return: The created_by of this Alert.  # noqa: E501
        :rtype: int
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this Alert.


        :param created_by: The created_by of this Alert.  # noqa: E501
        :type: int
        """

        self._created_by = created_by

    @property
    def updated_by(self):
        """Gets the updated_by of this Alert.  # noqa: E501


        :return: The updated_by of this Alert.  # noqa: E501
        :rtype: int
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this Alert.


        :param updated_by: The updated_by of this Alert.  # noqa: E501
        :type: int
        """

        self._updated_by = updated_by

    @property
    def hazard(self):
        """Gets the hazard of this Alert.  # noqa: E501


        :return: The hazard of this Alert.  # noqa: E501
        :rtype: int
        """
        return self._hazard

    @hazard.setter
    def hazard(self, hazard):
        """Sets the hazard of this Alert.


        :param hazard: The hazard of this Alert.  # noqa: E501
        :type: int
        """

        self._hazard = hazard

    @property
    def event(self):
        """Gets the event of this Alert.  # noqa: E501


        :return: The event of this Alert.  # noqa: E501
        :rtype: int
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this Alert.


        :param event: The event of this Alert.  # noqa: E501
        :type: int
        """

        self._event = event

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Alert, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Alert):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
