# coding: utf-8

"""
    BIPAD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Inventory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'item': 'Item',
        'item_id': 'int',
        'created_on': 'datetime',
        'modified_on': 'datetime',
        'quantity': 'int',
        'description': 'str',
        'resource': 'int'
    }

    attribute_map = {
        'id': 'id',
        'item': 'item',
        'item_id': 'itemId',
        'created_on': 'createdOn',
        'modified_on': 'modifiedOn',
        'quantity': 'quantity',
        'description': 'description',
        'resource': 'resource'
    }

    def __init__(self, id=None, item=None, item_id=None, created_on=None, modified_on=None, quantity=None, description=None, resource=None):  # noqa: E501
        """Inventory - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._item = None
        self._item_id = None
        self._created_on = None
        self._modified_on = None
        self._quantity = None
        self._description = None
        self._resource = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if item is not None:
            self.item = item
        self.item_id = item_id
        if created_on is not None:
            self.created_on = created_on
        if modified_on is not None:
            self.modified_on = modified_on
        self.quantity = quantity
        if description is not None:
            self.description = description
        self.resource = resource

    @property
    def id(self):
        """Gets the id of this Inventory.  # noqa: E501


        :return: The id of this Inventory.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Inventory.


        :param id: The id of this Inventory.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def item(self):
        """Gets the item of this Inventory.  # noqa: E501


        :return: The item of this Inventory.  # noqa: E501
        :rtype: Item
        """
        return self._item

    @item.setter
    def item(self, item):
        """Sets the item of this Inventory.


        :param item: The item of this Inventory.  # noqa: E501
        :type: Item
        """

        self._item = item

    @property
    def item_id(self):
        """Gets the item_id of this Inventory.  # noqa: E501


        :return: The item_id of this Inventory.  # noqa: E501
        :rtype: int
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id):
        """Sets the item_id of this Inventory.


        :param item_id: The item_id of this Inventory.  # noqa: E501
        :type: int
        """
        if item_id is None:
            raise ValueError("Invalid value for `item_id`, must not be `None`")  # noqa: E501

        self._item_id = item_id

    @property
    def created_on(self):
        """Gets the created_on of this Inventory.  # noqa: E501


        :return: The created_on of this Inventory.  # noqa: E501
        :rtype: datetime
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """Sets the created_on of this Inventory.


        :param created_on: The created_on of this Inventory.  # noqa: E501
        :type: datetime
        """

        self._created_on = created_on

    @property
    def modified_on(self):
        """Gets the modified_on of this Inventory.  # noqa: E501


        :return: The modified_on of this Inventory.  # noqa: E501
        :rtype: datetime
        """
        return self._modified_on

    @modified_on.setter
    def modified_on(self, modified_on):
        """Sets the modified_on of this Inventory.


        :param modified_on: The modified_on of this Inventory.  # noqa: E501
        :type: datetime
        """

        self._modified_on = modified_on

    @property
    def quantity(self):
        """Gets the quantity of this Inventory.  # noqa: E501


        :return: The quantity of this Inventory.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this Inventory.


        :param quantity: The quantity of this Inventory.  # noqa: E501
        :type: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501
        if quantity is not None and quantity > 2147483647:  # noqa: E501
            raise ValueError("Invalid value for `quantity`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if quantity is not None and quantity < 0:  # noqa: E501
            raise ValueError("Invalid value for `quantity`, must be a value greater than or equal to `0`")  # noqa: E501

        self._quantity = quantity

    @property
    def description(self):
        """Gets the description of this Inventory.  # noqa: E501


        :return: The description of this Inventory.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Inventory.


        :param description: The description of this Inventory.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def resource(self):
        """Gets the resource of this Inventory.  # noqa: E501


        :return: The resource of this Inventory.  # noqa: E501
        :rtype: int
        """
        return self._resource

    @resource.setter
    def resource(self, resource):
        """Sets the resource of this Inventory.


        :param resource: The resource of this Inventory.  # noqa: E501
        :type: int
        """
        if resource is None:
            raise ValueError("Invalid value for `resource`, must not be `None`")  # noqa: E501

        self._resource = resource

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Inventory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Inventory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
