# coding: utf-8

"""
    BIPAD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Organization(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'title': 'str',
        'short_name': 'str',
        'long_name': 'str',
        'description': 'str',
        'incident_verification_duration': 'int',
        'responsible_for': 'list[int]',
        'wards': 'list[int]'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'short_name': 'shortName',
        'long_name': 'longName',
        'description': 'description',
        'incident_verification_duration': 'incidentVerificationDuration',
        'responsible_for': 'responsibleFor',
        'wards': 'wards'
    }

    def __init__(self, id=None, title=None, short_name=None, long_name=None, description=None, incident_verification_duration=None, responsible_for=None, wards=None):  # noqa: E501
        """Organization - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._title = None
        self._short_name = None
        self._long_name = None
        self._description = None
        self._incident_verification_duration = None
        self._responsible_for = None
        self._wards = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.title = title
        if short_name is not None:
            self.short_name = short_name
        if long_name is not None:
            self.long_name = long_name
        if description is not None:
            self.description = description
        if incident_verification_duration is not None:
            self.incident_verification_duration = incident_verification_duration
        if responsible_for is not None:
            self.responsible_for = responsible_for
        self.wards = wards

    @property
    def id(self):
        """Gets the id of this Organization.  # noqa: E501


        :return: The id of this Organization.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Organization.


        :param id: The id of this Organization.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this Organization.  # noqa: E501


        :return: The title of this Organization.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Organization.


        :param title: The title of this Organization.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501
        if title is not None and len(title) > 255:
            raise ValueError("Invalid value for `title`, length must be less than or equal to `255`")  # noqa: E501
        if title is not None and len(title) < 1:
            raise ValueError("Invalid value for `title`, length must be greater than or equal to `1`")  # noqa: E501

        self._title = title

    @property
    def short_name(self):
        """Gets the short_name of this Organization.  # noqa: E501


        :return: The short_name of this Organization.  # noqa: E501
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """Sets the short_name of this Organization.


        :param short_name: The short_name of this Organization.  # noqa: E501
        :type: str
        """
        if short_name is not None and len(short_name) > 255:
            raise ValueError("Invalid value for `short_name`, length must be less than or equal to `255`")  # noqa: E501

        self._short_name = short_name

    @property
    def long_name(self):
        """Gets the long_name of this Organization.  # noqa: E501


        :return: The long_name of this Organization.  # noqa: E501
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name):
        """Sets the long_name of this Organization.


        :param long_name: The long_name of this Organization.  # noqa: E501
        :type: str
        """
        if long_name is not None and len(long_name) > 255:
            raise ValueError("Invalid value for `long_name`, length must be less than or equal to `255`")  # noqa: E501

        self._long_name = long_name

    @property
    def description(self):
        """Gets the description of this Organization.  # noqa: E501


        :return: The description of this Organization.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Organization.


        :param description: The description of this Organization.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def incident_verification_duration(self):
        """Gets the incident_verification_duration of this Organization.  # noqa: E501


        :return: The incident_verification_duration of this Organization.  # noqa: E501
        :rtype: int
        """
        return self._incident_verification_duration

    @incident_verification_duration.setter
    def incident_verification_duration(self, incident_verification_duration):
        """Sets the incident_verification_duration of this Organization.


        :param incident_verification_duration: The incident_verification_duration of this Organization.  # noqa: E501
        :type: int
        """
        if incident_verification_duration is not None and incident_verification_duration > 2147483647:  # noqa: E501
            raise ValueError("Invalid value for `incident_verification_duration`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if incident_verification_duration is not None and incident_verification_duration < 0:  # noqa: E501
            raise ValueError("Invalid value for `incident_verification_duration`, must be a value greater than or equal to `0`")  # noqa: E501

        self._incident_verification_duration = incident_verification_duration

    @property
    def responsible_for(self):
        """Gets the responsible_for of this Organization.  # noqa: E501


        :return: The responsible_for of this Organization.  # noqa: E501
        :rtype: list[int]
        """
        return self._responsible_for

    @responsible_for.setter
    def responsible_for(self, responsible_for):
        """Sets the responsible_for of this Organization.


        :param responsible_for: The responsible_for of this Organization.  # noqa: E501
        :type: list[int]
        """

        self._responsible_for = responsible_for

    @property
    def wards(self):
        """Gets the wards of this Organization.  # noqa: E501


        :return: The wards of this Organization.  # noqa: E501
        :rtype: list[int]
        """
        return self._wards

    @wards.setter
    def wards(self, wards):
        """Sets the wards of this Organization.


        :param wards: The wards of this Organization.  # noqa: E501
        :type: list[int]
        """
        if wards is None:
            raise ValueError("Invalid value for `wards`, must not be `None`")  # noqa: E501

        self._wards = wards

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Organization, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Organization):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
