# coding: utf-8

"""
    BIPAD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Reconstruction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'damages': 'list[int]',
        'description': 'str',
        'organization': 'str',
        'event': 'int'
    }

    attribute_map = {
        'id': 'id',
        'damages': 'damages',
        'description': 'description',
        'organization': 'organization',
        'event': 'event'
    }

    def __init__(self, id=None, damages=None, description=None, organization=None, event=None):  # noqa: E501
        """Reconstruction - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._damages = None
        self._description = None
        self._organization = None
        self._event = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if damages is not None:
            self.damages = damages
        if description is not None:
            self.description = description
        if organization is not None:
            self.organization = organization
        self.event = event

    @property
    def id(self):
        """Gets the id of this Reconstruction.  # noqa: E501


        :return: The id of this Reconstruction.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Reconstruction.


        :param id: The id of this Reconstruction.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def damages(self):
        """Gets the damages of this Reconstruction.  # noqa: E501


        :return: The damages of this Reconstruction.  # noqa: E501
        :rtype: list[int]
        """
        return self._damages

    @damages.setter
    def damages(self, damages):
        """Sets the damages of this Reconstruction.


        :param damages: The damages of this Reconstruction.  # noqa: E501
        :type: list[int]
        """

        self._damages = damages

    @property
    def description(self):
        """Gets the description of this Reconstruction.  # noqa: E501


        :return: The description of this Reconstruction.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Reconstruction.


        :param description: The description of this Reconstruction.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def organization(self):
        """Gets the organization of this Reconstruction.  # noqa: E501


        :return: The organization of this Reconstruction.  # noqa: E501
        :rtype: str
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this Reconstruction.


        :param organization: The organization of this Reconstruction.  # noqa: E501
        :type: str
        """
        if organization is not None and len(organization) > 255:
            raise ValueError("Invalid value for `organization`, length must be less than or equal to `255`")  # noqa: E501

        self._organization = organization

    @property
    def event(self):
        """Gets the event of this Reconstruction.  # noqa: E501


        :return: The event of this Reconstruction.  # noqa: E501
        :rtype: int
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this Reconstruction.


        :param event: The event of this Reconstruction.  # noqa: E501
        :type: int
        """
        if event is None:
            raise ValueError("Invalid value for `event`, must not be `None`")  # noqa: E501

        self._event = event

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Reconstruction, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Reconstruction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
