# coding: utf-8

"""
    BIPAD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Ward(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'bbox': 'list[str]',
        'centroid': 'str',
        'title': 'str',
        'municipality': 'int'
    }

    attribute_map = {
        'id': 'id',
        'bbox': 'bbox',
        'centroid': 'centroid',
        'title': 'title',
        'municipality': 'municipality'
    }

    def __init__(self, id=None, bbox=None, centroid=None, title=None, municipality=None):  # noqa: E501
        """Ward - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._bbox = None
        self._centroid = None
        self._title = None
        self._municipality = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if bbox is not None:
            self.bbox = bbox
        if centroid is not None:
            self.centroid = centroid
        self.title = title
        self.municipality = municipality

    @property
    def id(self):
        """Gets the id of this Ward.  # noqa: E501


        :return: The id of this Ward.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Ward.


        :param id: The id of this Ward.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def bbox(self):
        """Gets the bbox of this Ward.  # noqa: E501


        :return: The bbox of this Ward.  # noqa: E501
        :rtype: list[str]
        """
        return self._bbox

    @bbox.setter
    def bbox(self, bbox):
        """Sets the bbox of this Ward.


        :param bbox: The bbox of this Ward.  # noqa: E501
        :type: list[str]
        """

        self._bbox = bbox

    @property
    def centroid(self):
        """Gets the centroid of this Ward.  # noqa: E501


        :return: The centroid of this Ward.  # noqa: E501
        :rtype: str
        """
        return self._centroid

    @centroid.setter
    def centroid(self, centroid):
        """Sets the centroid of this Ward.


        :param centroid: The centroid of this Ward.  # noqa: E501
        :type: str
        """

        self._centroid = centroid

    @property
    def title(self):
        """Gets the title of this Ward.  # noqa: E501


        :return: The title of this Ward.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Ward.


        :param title: The title of this Ward.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501
        if title is not None and len(title) > 25:
            raise ValueError("Invalid value for `title`, length must be less than or equal to `25`")  # noqa: E501
        if title is not None and len(title) < 1:
            raise ValueError("Invalid value for `title`, length must be greater than or equal to `1`")  # noqa: E501

        self._title = title

    @property
    def municipality(self):
        """Gets the municipality of this Ward.  # noqa: E501


        :return: The municipality of this Ward.  # noqa: E501
        :rtype: int
        """
        return self._municipality

    @municipality.setter
    def municipality(self, municipality):
        """Sets the municipality of this Ward.


        :param municipality: The municipality of this Ward.  # noqa: E501
        :type: int
        """
        if municipality is None:
            raise ValueError("Invalid value for `municipality`, must not be `None`")  # noqa: E501

        self._municipality = municipality

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Ward, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Ward):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
